pipeline {
    agent none
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            agent {
                docker{
                    image 'python:2-aplpine'
                }
            }
        }
        steps {
            sh 'python -m py_compile sources/addvals.py source/calc.py'
            stash(name: 'compiled-results', includes: 'sources/*.py*')
        }
    }
}
